### ISSUE TITLE
iOS support?

### ISSUE THREAD

**Issue by AhsanSarwar45** [imedboumalek/flutter_system_ringtones#2]
Hello, just found this package after searching for a long time for such functionality. Looks promising, but I was curious whether it supports iOS? There is an unchecked TODO in the readme for 'iOS: Get a list of available ringtones dynamically'. I was not sure what it meant so wanted to clear up. I haven't got a Mac/iOS device right now to test it but want to support iOS in the future.

**Comment by Aqitaniya** [comment]
Hello, the same question. I get an error on IOS:

flutter: type 'String' is not a subtype of type 'List<dynamic>?' in type cast
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: type 'String' is not a subtype of type 'List<dynamic>?' in type cast
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:41)
<asynchronous suspension>
#1      MethodChannelFlutterSystemRingtones.getNotifications (package:flutter_system_ringtones/flutter_system_ringtones_method_channel.dart:35:25)
<asynchronous suspension>
#2      FlutterSystemRingtones.getNotificationSounds (package:flutter_system_ringtones/flutter_system_ringtones.dart:25:12)
<asynchronous suspension>
